name: Laravel

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.4"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Generate JWT key
        run: php artisan jwt:secret --force

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run database migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          JWT_SECRET: testing_secret_key_for_github_actions
        run: php artisan migrate --force

      - name: Seed Database
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          JWT_SECRET: testing_secret_key_for_github_actions
        run: php artisan db:seed --force

      - name: Setup testing environment
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          JWT_SECRET: testing_secret_key_for_github_actions
        run: |
          php artisan config:clear
          php artisan view:clear

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          JWT_SECRET: testing_secret_key_for_github_actions
          APP_ENV: testing
          APP_KEY: base64:testing_key_for_github_actions
          VITE_APP_NAME: "${APP_NAME}"
        run: php artisan test
